verb(_, _, _) --> ["лететь"].
verb(sing, _, pres) --> ["лечу"].
verb(plur, _, pres) --> ["летим"].
verb(sing, _, pres) --> ["летишь"].
verb(plur, _, pres) --> ["летите"].
verb(sing, _, pres) --> ["летит"].
verb(plur, _, pres) --> ["летят"].
verb(sing, masc, past) --> ["летел"].
verb(sing, femn, past) --> ["летела"].
verb(sing, neut, past) --> ["летело"].
verb(plur, _, past) --> ["летели"].
verb(sing, _, _) --> ["летим"].
verb(plur, _, _) --> ["летимте"].
verb(sing, _, _) --> ["лети"].
verb(plur, _, _) --> ["летите"].
verb(sing, masc, pres) --> ["летящий"].
verb(sing, masc, pres) --> ["летящего"].
verb(sing, masc, pres) --> ["летящему"].
verb(sing, masc, pres) --> ["летящего"].
verb(sing, masc, pres) --> ["летящий"].
verb(sing, masc, pres) --> ["летящим"].
verb(sing, masc, pres) --> ["летящем"].
verb(sing, femn, pres) --> ["летящая"].
verb(sing, femn, pres) --> ["летящей"].
verb(sing, femn, pres) --> ["летящей"].
verb(sing, femn, pres) --> ["летящую"].
verb(sing, femn, pres) --> ["летящей"].
verb(sing, femn, pres) --> ["летящею"].
verb(sing, femn, pres) --> ["летящей"].
verb(sing, neut, pres) --> ["летящее"].
verb(sing, neut, pres) --> ["летящего"].
verb(sing, neut, pres) --> ["летящему"].
verb(sing, neut, pres) --> ["летящее"].
verb(sing, neut, pres) --> ["летящим"].
verb(sing, neut, pres) --> ["летящем"].
verb(plur, _, pres) --> ["летящие"].
verb(plur, _, pres) --> ["летящих"].
verb(plur, _, pres) --> ["летящим"].
verb(plur, _, pres) --> ["летящих"].
verb(plur, _, pres) --> ["летящие"].
verb(plur, _, pres) --> ["летящими"].
verb(plur, _, pres) --> ["летящих"].
verb(sing, masc, past) --> ["летевший"].
verb(sing, masc, past) --> ["летевшего"].
verb(sing, masc, past) --> ["летевшему"].
verb(sing, masc, past) --> ["летевшего"].
verb(sing, masc, past) --> ["летевший"].
verb(sing, masc, past) --> ["летевшим"].
verb(sing, masc, past) --> ["летевшем"].
verb(sing, femn, past) --> ["летевшая"].
verb(sing, femn, past) --> ["летевшей"].
verb(sing, femn, past) --> ["летевшей"].
verb(sing, femn, past) --> ["летевшую"].
verb(sing, femn, past) --> ["летевшей"].
verb(sing, femn, past) --> ["летевшею"].
verb(sing, femn, past) --> ["летевшей"].
verb(sing, neut, past) --> ["летевшее"].
verb(sing, neut, past) --> ["летевшего"].
verb(sing, neut, past) --> ["летевшему"].
verb(sing, neut, past) --> ["летевшее"].
verb(sing, neut, past) --> ["летевшим"].
verb(sing, neut, past) --> ["летевшем"].
verb(plur, _, past) --> ["летевшие"].
verb(plur, _, past) --> ["летевших"].
verb(plur, _, past) --> ["летевшим"].
verb(plur, _, past) --> ["летевших"].
verb(plur, _, past) --> ["летевшие"].
verb(plur, _, past) --> ["летевшими"].
verb(plur, _, past) --> ["летевших"].
verb(_, _, pres) --> ["летя"].
verb(_, _, past) --> ["летев"].
verb(_, _, past) --> ["летевши"].
adjective(sing, masc, nomn) --> ["умный"].
adjective(sing, masc, gent) --> ["умного"].
adjective(sing, masc, datv) --> ["умному"].
adjective(sing, masc, accs) --> ["умного"].
adjective(sing, masc, accs) --> ["умный"].
adjective(sing, masc, ablt) --> ["умным"].
adjective(sing, masc, loct) --> ["умном"].
adjective(sing, femn, nomn) --> ["умная"].
adjective(sing, femn, gent) --> ["умной"].
adjective(sing, femn, datv) --> ["умной"].
adjective(sing, femn, accs) --> ["умную"].
adjective(sing, femn, ablt) --> ["умной"].
adjective(sing, femn, ablt) --> ["умною"].
adjective(sing, femn, loct) --> ["умной"].
adjective(sing, neut, nomn) --> ["умное"].
adjective(sing, neut, gent) --> ["умного"].
adjective(sing, neut, datv) --> ["умному"].
adjective(sing, neut, accs) --> ["умное"].
adjective(sing, neut, ablt) --> ["умным"].
adjective(sing, neut, loct) --> ["умном"].
adjective(plur, _, nomn) --> ["умные"].
adjective(plur, _, gent) --> ["умных"].
adjective(plur, _, datv) --> ["умным"].
adjective(plur, _, accs) --> ["умных"].
adjective(plur, _, accs) --> ["умные"].
adjective(plur, _, ablt) --> ["умными"].
adjective(plur, _, loct) --> ["умных"].
adjective(sing, masc, nomn) --> ["умнейший"].
adjective(sing, masc, gent) --> ["умнейшего"].
adjective(sing, masc, datv) --> ["умнейшему"].
adjective(sing, masc, accs) --> ["умнейшего"].
adjective(sing, masc, accs) --> ["умнейший"].
adjective(sing, masc, ablt) --> ["умнейшим"].
adjective(sing, masc, loct) --> ["умнейшем"].
adjective(sing, femn, nomn) --> ["умнейшая"].
adjective(sing, femn, gent) --> ["умнейшей"].
adjective(sing, femn, datv) --> ["умнейшей"].
adjective(sing, femn, accs) --> ["умнейшую"].
adjective(sing, femn, ablt) --> ["умнейшей"].
adjective(sing, femn, ablt) --> ["умнейшею"].
adjective(sing, femn, loct) --> ["умнейшей"].
adjective(sing, neut, nomn) --> ["умнейшее"].
adjective(sing, neut, gent) --> ["умнейшего"].
adjective(sing, neut, datv) --> ["умнейшему"].
adjective(sing, neut, accs) --> ["умнейшее"].
adjective(sing, neut, ablt) --> ["умнейшим"].
adjective(sing, neut, loct) --> ["умнейшем"].
adjective(plur, _, nomn) --> ["умнейшие"].
adjective(plur, _, gent) --> ["умнейших"].
adjective(plur, _, datv) --> ["умнейшим"].
adjective(plur, _, accs) --> ["умнейших"].
adjective(plur, _, accs) --> ["умнейшие"].
adjective(plur, _, ablt) --> ["умнейшими"].
adjective(plur, _, loct) --> ["умнейших"].
adjective(sing, masc, _) --> ["умён"].
adjective(sing, femn, _) --> ["умна"].
adjective(sing, neut, _) --> ["умно"].
adjective(plur, _, _) --> ["умны"].
adjective(_, _, _) --> ["умнее"].
adjective(_, _, _) --> ["умней"].
adjective(_, _, _) --> ["поумнее"].
adjective(_, _, _) --> ["поумней"].
adjective(sing, masc, nomn) --> ["наиумнейший"].
adjective(sing, masc, gent) --> ["наиумнейшего"].
adjective(sing, masc, datv) --> ["наиумнейшему"].
adjective(sing, masc, accs) --> ["наиумнейшего"].
adjective(sing, masc, accs) --> ["наиумнейший"].
adjective(sing, masc, ablt) --> ["наиумнейшим"].
adjective(sing, masc, loct) --> ["наиумнейшем"].
adjective(sing, femn, nomn) --> ["наиумнейшая"].
adjective(sing, femn, gent) --> ["наиумнейшей"].
adjective(sing, femn, datv) --> ["наиумнейшей"].
adjective(sing, femn, accs) --> ["наиумнейшую"].
adjective(sing, femn, ablt) --> ["наиумнейшей"].
adjective(sing, femn, ablt) --> ["наиумнейшею"].
adjective(sing, femn, loct) --> ["наиумнейшей"].
adjective(sing, neut, nomn) --> ["наиумнейшее"].
adjective(sing, neut, gent) --> ["наиумнейшего"].
adjective(sing, neut, datv) --> ["наиумнейшему"].
adjective(sing, neut, accs) --> ["наиумнейшее"].
adjective(sing, neut, ablt) --> ["наиумнейшим"].
adjective(sing, neut, loct) --> ["наиумнейшем"].
adjective(plur, _, nomn) --> ["наиумнейшие"].
adjective(plur, _, gent) --> ["наиумнейших"].
adjective(plur, _, datv) --> ["наиумнейшим"].
adjective(plur, _, accs) --> ["наиумнейших"].
adjective(plur, _, accs) --> ["наиумнейшие"].
adjective(plur, _, ablt) --> ["наиумнейшими"].
adjective(plur, _, loct) --> ["наиумнейших"].
noun(sing, masc, nomn) --> ["гусь"].
noun(sing, masc, gent) --> ["гуся"].
noun(sing, masc, datv) --> ["гусю"].
noun(sing, masc, accs) --> ["гуся"].
noun(sing, masc, ablt) --> ["гусем"].
noun(sing, masc, loct) --> ["гусе"].
noun(plur, masc, nomn) --> ["гуси"].
noun(plur, masc, gent) --> ["гусей"].
noun(plur, masc, datv) --> ["гусям"].
noun(plur, masc, accs) --> ["гусей"].
noun(plur, masc, ablt) --> ["гусями"].
noun(plur, masc, loct) --> ["гусях"].
adverb() --> ["быстро"].
pronoun(sing, masc, nomn) --> ["он"].
pronoun(sing, masc, gent) --> ["его"].
pronoun(sing, masc, gent) --> ["него"].
pronoun(sing, masc, datv) --> ["ему"].
pronoun(sing, masc, datv) --> ["нему"].
pronoun(sing, masc, accs) --> ["его"].
pronoun(sing, masc, accs) --> ["него"].
pronoun(sing, masc, ablt) --> ["им"].
pronoun(sing, masc, ablt) --> ["ним"].
pronoun(sing, masc, loct) --> ["нём"].
adjective(sing, masc, nomn) --> ["ближний"].
adjective(sing, masc, gent) --> ["ближнего"].
adjective(sing, masc, datv) --> ["ближнему"].
adjective(sing, masc, accs) --> ["ближнего"].
adjective(sing, masc, accs) --> ["ближний"].
adjective(sing, masc, ablt) --> ["ближним"].
adjective(sing, masc, loct) --> ["ближнем"].
adjective(sing, femn, nomn) --> ["ближняя"].
adjective(sing, femn, gent) --> ["ближней"].
adjective(sing, femn, datv) --> ["ближней"].
adjective(sing, femn, accs) --> ["ближнюю"].
adjective(sing, femn, ablt) --> ["ближней"].
adjective(sing, femn, ablt) --> ["ближнею"].
adjective(sing, femn, loct) --> ["ближней"].
adjective(sing, neut, nomn) --> ["ближнее"].
adjective(sing, neut, gent) --> ["ближнего"].
adjective(sing, neut, datv) --> ["ближнему"].
adjective(sing, neut, accs) --> ["ближнее"].
adjective(sing, neut, ablt) --> ["ближним"].
adjective(sing, neut, loct) --> ["ближнем"].
adjective(plur, _, nomn) --> ["ближние"].
adjective(plur, _, gent) --> ["ближних"].
adjective(plur, _, datv) --> ["ближним"].
adjective(plur, _, accs) --> ["ближних"].
adjective(plur, _, accs) --> ["ближние"].
adjective(plur, _, ablt) --> ["ближними"].
adjective(plur, _, loct) --> ["ближних"].
adjective(sing, femn, _) --> ["ближня"].
adjective(sing, neut, _) --> ["ближне"].
adjective(plur, _, _) --> ["ближни"].
noun(sing, femn, nomn) --> ["даль"].
noun(sing, femn, gent) --> ["дали"].
noun(sing, femn, datv) --> ["дали"].
noun(sing, femn, accs) --> ["даль"].
noun(sing, femn, ablt) --> ["далью"].
noun(sing, femn, loct) --> ["дали"].
noun(sing, femn, loc2) --> ["дали"].
noun(plur, femn, nomn) --> ["дали"].
noun(plur, femn, gent) --> ["далей"].
noun(plur, femn, datv) --> ["далям"].
noun(plur, femn, accs) --> ["дали"].
noun(plur, femn, ablt) --> ["далями"].
noun(plur, femn, loct) --> ["далях"].
